### ISSUE TITLE
Question about ADDB sample generation?

### ISSUE THREAD

**Issue by huijunjin** [addb-swstarlab/ADDB_sample_generation#2]
If ADDB consists of several tiers, how do you know where the bottleneck of performance of ADDB is, especially when you have multiple configuration files simultaneously? Or does it not matter?

**Comment by JIEUN-12** [comment]
It's hard to recognize where the bottleneck of performance of ADDB is. We will analyze their relationship by machine learning methodologies. 

Thanks for asking!
