### ISSUE TITLE
About string_categorical knob sampling.

### ISSUE THREAD

**Issue by Kwon-sein** [addb-swstarlab/ADDB_sample_generation#5]
Hi!

I have a question about LHS sampling. 
For continuous knob values, numerical sampling is possible, but how did you perform sampling on knobs with string values?

If there are only two values ​​to choose (ex, True or False ) , it can be expressed as 0 or 1. 
But how can sampling when there are three or more values?

Thanks for reading :)

**Comment by JIEUN-12** [comment]
Firstly, we did not include such cases where knobs have three or more values.

However, I think that when the knob has three or more values, it can be expressed as numbers like [1, 2, 3, 4 ..].
